---
- hosts: webserver
  remote_user: vagrant
  become: yes
  become_method: sudo
  roles:
    - apache

- hosts: dbserver
  remote_user: vagrant
  become: yes
  become_method: sudo
  roles:
    - db
